# ~/.config/alacritty/alacritty.toml

[window]
# decorations = "none"
opacity = 1
padding.x = 5
padding.y = 0

[font]
normal.family = "JetBrains Mono"
normal.style = "Bold"
size = 12.0

[font.offset]
x = 0
y = -1

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#D8DEE9"

[colors.bright]
black   = "#4C556A"
red     = "#D16976"
green   = "#B4D18F"
yellow  = "#F0D193"
blue    = "#90B3D9"
magenta = "#C69BC0"
cyan    = "#9FD1D3"
white   = "#ECEFF4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#434C5E"
