"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](nord0)\
$os\
$username\
[](bg:nord9 fg:nord0)\
$directory\
[](fg:nord9 bg:nord7)\
$git_branch\
$git_status\
[](fg:nord7 bg:nord8)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:nord8 bg:nord10)\
$docker_context\
[](fg:nord10 bg:nord2)\
$time\
[ ](fg:nord2)\
$line_break$character"""

palette = 'nord'

[palettes.nord]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"

[os]
disabled = false
style = "bg:nord0 fg:nord4"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:nord0 fg:nord4"
style_root = "bg:nord0 fg:nord4"
format = '[ $user ]($style)'

[directory]
style = "fg:nord0 bg:nord9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:nord7"
format = '[[ $symbol $branch ](fg:nord0 bg:nord7)]($style)'

[git_status]
style = "bg:nord7"
format = '[[($all_status$ahead_behind )](fg:nord0 bg:nord7)]($style)'

[nodejs]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[c]
symbol = " "
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[rust]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[golang]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[php]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[java]
symbol = " "
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[kotlin]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[haskell]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[python]
symbol = ""
style = "bg:nord8"
format = '[[ $symbol( $version) ](fg:nord0 bg:nord8)]($style)'

[docker_context]
symbol = ""
style = "bg:nord10"
format = '[[ $symbol( $context) ](fg:nord4 bg:nord10)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:nord2"
format = '[[  $time ](fg:nord4 bg:nord2)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:nord7)'
error_symbol = '[](bold fg:nord9)'
vimcmd_symbol = '[](bold fg:nord8)'
vimcmd_replace_one_symbol = '[](bold fg:nord10)'
vimcmd_replace_symbol = '[](bold fg:nord10)'
vimcmd_visual_symbol = '[](bold fg:nord7)'
